package ast;

public enum TExp {
	  SUMA, RESTA, MASMAS, MENOSMENOS, MULT, DIV, ENTERO, REAL, MODULO,
	  NOT, AND, OR, MAYOR, MENOR, MAYORIGUAL, IGUAL, 
	  MENORIGUAL, IGUALIGUAL, DISTINTO, CORCHETES, ACCESOENUM, ACCESOSTRUCT, TRUE, FALSE, 
	  CARACTER, IDEN, CALL
	}