
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 30 17:44:06 CEST 2021
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MASMAS = 25;
  public static final int DISTINTO = 33;
  public static final int MENOSMENOS = 26;
  public static final int LLCIERRE = 12;
  public static final int CHAR = 4;
  public static final int CCIERRE = 8;
  public static final int PCIERRE = 10;
  public static final int ENTERO = 46;
  public static final int RESTA = 28;
  public static final int ACCESOSTRUCT = 50;
  public static final int CAP = 7;
  public static final int INT = 2;
  public static final int PUNTOCOMA = 14;
  public static final int FOR = 39;
  public static final int NOT = 36;
  public static final int MENORIGUAL = 21;
  public static final int AND = 34;
  public static final int IGUAL = 31;
  public static final int CARACTER = 48;
  public static final int FUN = 44;
  public static final int LLAP = 11;
  public static final int OR = 35;
  public static final int BOOL = 3;
  public static final int CALL = 45;
  public static final int DIV = 30;
  public static final int ACCESOENUM = 51;
  public static final int SUMA = 27;
  public static final int IF = 22;
  public static final int MAYORIGUAL = 20;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int MODULO = 37;
  public static final int MENOR = 19;
  public static final int VOID = 42;
  public static final int REAL = 47;
  public static final int MAYOR = 18;
  public static final int PAP = 9;
  public static final int BARRA = 17;
  public static final int ELSE = 23;
  public static final int ENUM = 41;
  public static final int IDEN = 6;
  public static final int IGUALIGUAL = 32;
  public static final int WHILE = 38;
  public static final int FLOAT = 5;
  public static final int MULTI = 29;
  public static final int FALSE = 16;
  public static final int STRUCT = 40;
  public static final int ELIF = 24;
  public static final int PRINT = 49;
}

